import { join } from 'path';
import { aws_ec2, aws_iam, aws_lambda, aws_logs, Duration, Stack, Stage } from 'aws-cdk-lib';
import { Construct } from 'constructs';

/** Default SSM parameter path holding per-queue replay configs. */
export const DEFAULT_CONFIG_PATH = '/sqs-replay/queues/';

const SINGLETON_ID = 'SqsReplayerSingleton';
const singletons = new WeakMap<Stage, SqsReplayerSingleton>();

export interface SqsReplayerSingletonProps {
  /**
   * Memory allocated to the replayer Lambda.
   * @default 256
   */
  readonly memorySize?: number;
  /**
   * Timeout for the replayer Lambda.
   * @default Duration.seconds(10)
   */
  readonly timeout?: Duration;
  /**
   * Log retention for the replayer Lambda's log group.
   * @default - keep logs indefinitely
   */
  readonly logRetention?: aws_logs.RetentionDays;
  /**
   * Name of the replayer Lambda function.
   * @default - generated by AWS CloudFormation
   */
  readonly functionName?: string;
  /**
   * VPC to place the replayer Lambda in.
   * @default - no VPC
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * Subnets to place the replayer Lambda in. Only used when `vpc` is set.
   * @default - private subnets of `vpc`
   */
  readonly vpcSubnets?: aws_ec2.SubnetSelection;
  /**
   * Additional environment variables for the replayer Lambda.
   * @default - no additional environment variables
   */
  readonly environment?: { [key: string]: string };
  /**
   * Override the Lambda code. Defaults to the prebuilt Rust binary shipped
   * with this package.
   * @default - prebuilt Rust binary bundled with this package
   */
  readonly code?: aws_lambda.Code;
  /**
   * SSM parameter path under which per-queue replay configs are stored.
   * @default "/sqs-replay/queues/"
   */
  readonly configPath?: string;
}

/**
 * The shared replayer Lambda for an app. One function serves every replay
 * queue in the app; each queue registers its destination in SSM Parameter
 * Store and the Lambda resolves it per event via the replay queue ARN.
 *
 * This construct is internal to the library and should not be used directly.
 */
export class SqsReplayerSingleton extends Construct {
  /**
   * Returns the app-scoped replayer singleton, creating it in the caller's
   * stack on first use.
   */
  public static of(scope: Construct, props: SqsReplayerSingletonProps): SqsReplayerSingleton {
    const stage = Stage.of(scope);
    if (!stage) {
      throw new Error('SqsReplayerSingleton must be used within an AWS CDK App');
    }
    const existing = singletons.get(stage);
    if (existing) {
      return existing;
    }
    const singleton = new SqsReplayerSingleton(Stack.of(scope), SINGLETON_ID, props);
    singletons.set(stage, singleton);
    return singleton;
  }

  /**
   * The shared replayer Lambda function.
   */
  public readonly replayer: aws_lambda.IFunction;
  /**
   * SSM parameter path under which per-queue replay configs are stored.
   */
  public readonly configPath: string;

  private constructor(scope: Construct, id: string, props: SqsReplayerSingletonProps) {
    super(scope, id);

    const {
      memorySize = 256,
      timeout = Duration.seconds(10),
      logRetention,
      functionName,
      vpc,
      vpcSubnets,
      code,
      environment,
      configPath = DEFAULT_CONFIG_PATH,
    } = props;

    this.configPath = configPath;

    const fn = new aws_lambda.Function(this, 'Replayer', {
      runtime: aws_lambda.Runtime.PROVIDED_AL2023,
      architecture: aws_lambda.Architecture.ARM_64,
      handler: 'bootstrap',
      code: code ?? aws_lambda.Code.fromAsset(join(__dirname, '..', 'assets', 'lambda')),
      memorySize,
      timeout,
      tracing: aws_lambda.Tracing.ACTIVE,
      environment: {
        SSM_PARAMETER_PATH: configPath,
        RUST_LOG: 'info',
        ...environment,
      },
      functionName,
      vpc,
      vpcSubnets,
      description: 'Replays messages back to their source queues, with exponential backoff.',
      ...(logRetention !== undefined ? { logRetention } : {}),
    });

    const pathArn = Stack.of(this).formatArn({
      service: 'ssm',
      resource: 'parameter',
      resourceName: `${configPath.replace(/^\//, '')}*`,
    });
    fn.addToRolePolicy(
      new aws_iam.PolicyStatement({
        actions: ['ssm:GetParametersByPath'],
        resources: [pathArn],
      }),
    );

    this.replayer = fn;
  }
}
