import { join } from 'path';
import {
  aws_ec2,
  aws_lambda,
  aws_lambda_event_sources,
  aws_logs,
  aws_sqs,
  Duration,
} from 'aws-cdk-lib';
import { Construct } from 'constructs';

export interface SqsReplayerProps {
  /**
   * Queue to send messages back to.
   */
  readonly sourceQueue: aws_sqs.IQueue;
  /**
   * Queue that triggers the replayer, typically the DLQ of `sourceQueue`.
   */
  readonly replayQueue: aws_sqs.IQueue;
  /**
   * Maximum replay attempts before a message is reported as a batch item
   * failure. Applied by the Lambda when not set.
   * @default 5
   */
  readonly maxAttempts?: number;
  /**
   * Multiplier for the backoff calculation. Applied by the Lambda when not
   * set.
   * @default Duration.seconds(30)
   */
  readonly backoffRate?: Duration;
  /**
   * Upper bound on the delay applied to each replayed message. Applied by the
   * Lambda when not set.
   * @default Duration.minutes(15)
   */
  readonly maximumDelay?: Duration;
  /**
   * Memory allocated to the replayer Lambda.
   * @default 512
   */
  readonly memorySize?: number;
  /**
   * Timeout for the replayer Lambda.
   * @default Duration.seconds(10)
   */
  readonly timeout?: Duration;
  /**
   * Log retention for the replayer Lambda's log group.
   * @default - keep logs indefinitely
   */
  readonly logRetention?: aws_logs.RetentionDays;
  /**
   * Name of the replayer Lambda function.
   * @default - generated by AWS CloudFormation
   */
  readonly functionName?: string;
  /**
   * VPC to place the replayer Lambda in.
   * @default - no VPC
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * Subnets to place the replayer Lambda in. Only used when `vpc` is set.
   * @default - private subnets of `vpc`
   */
  readonly vpcSubnets?: aws_ec2.SubnetSelection;
  /**
   * Additional environment variables for the replayer Lambda.
   * @default - no additional environment variables
   */
  readonly environment?: { [key: string]: string };
  /**
   * Override the Lambda code. Defaults to the prebuilt Rust binary shipped
   * with this package.
   * @default - prebuilt Rust binary bundled with this package
   */
  readonly code?: aws_lambda.Code;
}

/**
 * A Rust Lambda that replays SQS messages back to a source queue with
 * exponential backoff.
 */
export class SqsReplayer extends Construct {
  /**
   * The replayer Lambda function.
   */
  public readonly replayer: aws_lambda.IFunction;

  constructor(scope: Construct, id: string, props: SqsReplayerProps) {
    super(scope, id);

    const {
      sourceQueue,
      replayQueue,
      memorySize = 512,
      timeout = Duration.seconds(10),
      logRetention,
      functionName,
      vpc,
      vpcSubnets,
      environment,
      code,
    } = props;

    const lambdaEnvironment: { [key: string]: string } = {
      QUEUE_URL: sourceQueue.queueUrl,
      RUST_LOG: 'info',
      ...environment,
    };
    if (props.maxAttempts !== undefined) {
      lambdaEnvironment.MAX_ATTEMPTS = props.maxAttempts.toString();
    }
    if (props.backoffRate !== undefined) {
      lambdaEnvironment.BACKOFF_RATE = props.backoffRate.toSeconds().toString();
    }
    if (props.maximumDelay !== undefined) {
      lambdaEnvironment.MAXIMUM_DELAY = props.maximumDelay.toSeconds().toString();
    }

    this.replayer = new aws_lambda.Function(this, 'Replayer', {
      runtime: aws_lambda.Runtime.PROVIDED_AL2023,
      architecture: aws_lambda.Architecture.ARM_64,
      handler: 'bootstrap',
      code: code ?? aws_lambda.Code.fromAsset(join(__dirname, '..', 'assets', 'lambda')),
      memorySize,
      timeout,
      environment: lambdaEnvironment,
      functionName,
      vpc,
      vpcSubnets,
      description: 'Replays messages to the source queue, with exponential backoff.',
      ...(logRetention !== undefined ? { logRetention } : {}),
    });

    this.replayer.addEventSource(
      new aws_lambda_event_sources.SqsEventSource(replayQueue, {
        batchSize: 1,
        reportBatchItemFailures: true,
      }),
    );

    sourceQueue.grantSendMessages(this.replayer);
  }
}