import { aws_ec2, aws_lambda, aws_lambda_event_sources, aws_logs, aws_sqs, aws_ssm, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SqsReplayerSingleton } from './sqs-replayer-singleton';

export interface SqsReplayerProps {
  /**
   * Queue to send messages back to.
   */
  readonly sourceQueue: aws_sqs.IQueue;
  /**
   * Queue that triggers the replayer, typically the DLQ of `sourceQueue`.
   */
  readonly replayQueue: aws_sqs.IQueue;
  /**
   * Maximum replay attempts before a message is reported as a batch item
   * failure. Applied by the Lambda when not set.
   * @default 5
   */
  readonly maxAttempts?: number;
  /**
   * Multiplier for the backoff calculation. Applied by the Lambda when not
   * set.
   * @default Duration.seconds(30)
   */
  readonly backoffRate?: Duration;
  /**
   * Upper bound on the delay applied to each replayed message. Applied by the
   * Lambda when not set.
   * @default Duration.minutes(15)
   */
  readonly maximumDelay?: Duration;
  /**
   * Whether to add full jitter to the backoff delay. Applied by the Lambda
   * when not set.
   * @default false
   */
  readonly useJitter?: boolean;
  /**
   * Maximum number of messages the Lambda processes in a single invocation.
   * Larger batches reduce per-message overhead (fewer invocations and SSM
   * refreshes), at the cost of a longer-running invocation.
   * @default 10
   */
  readonly batchSize?: number;
  /**
   * Memory allocated to the replayer Lambda. Applies to the shared Lambda the
   * first time it is created.
   * @default 256
   */
  readonly memorySize?: number;
  /**
   * Timeout for the replayer Lambda. Applies to the shared Lambda the first
   * time it is created.
   * @default Duration.seconds(10)
   */
  readonly timeout?: Duration;
  /**
   * Log retention for the replayer Lambda's log group. Applies to the shared
   * Lambda the first time it is created.
   * @default - keep logs indefinitely
   */
  readonly logRetention?: aws_logs.RetentionDays;
  /**
   * Name of the replayer Lambda function. Applies to the shared Lambda the
   * first time it is created.
   * @default - generated by AWS CloudFormation
   */
  readonly functionName?: string;
  /**
   * VPC to place the replayer Lambda in. Applies to the shared Lambda the
   * first time it is created.
   * @default - no VPC
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * Subnets to place the replayer Lambda in. Only used when `vpc` is set.
   * @default - private subnets of `vpc`
   */
  readonly vpcSubnets?: aws_ec2.SubnetSelection;
  /**
   * Additional environment variables for the replayer Lambda. Applies to the
   * shared Lambda the first time it is created.
   * @default - no additional environment variables
   */
  readonly environment?: { [key: string]: string };
  /**
   * Override the Lambda code. Defaults to the prebuilt Rust binary shipped
   * with this package. Applies to the shared Lambda the first time it is
   * created.
   * @default - prebuilt Rust binary bundled with this package
   */
  readonly code?: aws_lambda.Code;
  /**
   * SSM parameter path under which per-queue replay configs are stored.
   * Applies to the shared Lambda the first time it is created.
   * @default "/sqs-replay/queues/"
   */
  readonly configPath?: string;
}

/**
 * Registers a replay queue with the app's shared replayer Lambda. The Lambda
 * resolves the destination queue from SSM Parameter Store using each event's
 * replay queue ARN, and replays messages back to it with exponential backoff.
 */
export class SqsReplayer extends Construct {
  /**
   * The shared replayer Lambda function.
   */
  public readonly replayer: aws_lambda.IFunction;

  constructor(scope: Construct, id: string, props: SqsReplayerProps) {
    super(scope, id);

    if (props.sourceQueue.fifo) {
      throw new Error(
        'SqsReplayer does not support FIFO queues: SQS does not support per-message delays on FIFO queues and its 5-minute deduplication window silently drops replayed copies. Use a standard queue.',
      );
    }
    validateTuning(props);

    const singleton = SqsReplayerSingleton.of(this, {
      memorySize: props.memorySize,
      timeout: props.timeout,
      logRetention: props.logRetention,
      functionName: props.functionName,
      vpc: props.vpc,
      vpcSubnets: props.vpcSubnets,
      environment: props.environment,
      code: props.code,
      configPath: props.configPath,
    });

    const { batchSize = 10, sourceQueue, replayQueue, maxAttempts, backoffRate, maximumDelay, useJitter } = props;
    const config: { [key: string]: string | number | boolean } = {
      replayQueueArn: replayQueue.queueArn,
      destinationQueueUrl: sourceQueue.queueUrl,
    };
    if (maxAttempts !== undefined) {
      config.maxAttempts = maxAttempts;
    }
    if (backoffRate !== undefined) {
      config.backoffRate = backoffRate.toSeconds();
    }
    if (maximumDelay !== undefined) {
      config.maximumDelay = maximumDelay.toSeconds();
    }
    if (useJitter !== undefined) {
      config.useJitter = useJitter;
    }

    const parameterName = `${singleton.configPath}${sanitize(this.node.path)}`;
    new aws_ssm.StringParameter(this, 'Config', {
      parameterName,
      stringValue: JSON.stringify(config),
    });

    singleton.replayer.addEventSource(
      new aws_lambda_event_sources.SqsEventSource(replayQueue, {
        batchSize,
        reportBatchItemFailures: true,
      }),
    );

    sourceQueue.grantSendMessages(singleton.replayer);

    this.replayer = singleton.replayer;
  }
}

/** Keeps construct paths valid as SSM parameter names. */
const sanitize = (value: string) => value.replace(/[^a-zA-Z0-9_./-]/g, '-');

/** Validates the backoff tuning options the construct writes to SSM. */
const validateTuning = (props: SqsReplayerProps): void => {
  if (props.maxAttempts !== undefined && props.maxAttempts < 1) {
    throw new Error('maxAttempts must be at least 1');
  }
  if (props.backoffRate !== undefined) {
    const backoffRate = props.backoffRate.toSeconds();
    if (backoffRate < 1) {
      throw new Error('backoffRate must be at least 1 second');
    }
  }
  if (props.maximumDelay !== undefined) {
    const maximumDelay = props.maximumDelay.toSeconds();
    if (maximumDelay < 1 || maximumDelay > 900) {
      throw new Error('maximumDelay must be between 1 second and 15 minutes');
    }
  }
  if (props.batchSize !== undefined && (props.batchSize < 1 || props.batchSize > 10000)) {
    throw new Error('batchSize must be between 1 and 10000');
  }
};
