import { aws_lambda, aws_logs, aws_sqs, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SqsReplayer } from './sqs-replayer';

export interface SqsQueueWithReplayProps {
  /**
   * Whether the queues are FIFO.
   * @default false
   */
  readonly fifo?: boolean;
  /**
   * Visibility timeout for the queues. Should be set to at least 6 times the
   * consuming Lambda's timeout.
   * @default Duration.seconds(18)
   */
  readonly visibilityTimeout?: Duration;
  /**
   * Number of receives before a message is redriven to the next queue.
   * @default 5
   */
  readonly maxReceiveCount?: number;
  /**
   * Maximum replay attempts before a message is dead-lettered. Applied by the
   * Lambda when not set.
   * @default 5
   */
  readonly maxAttempts?: number;
  /**
   * Multiplier for the backoff calculation. Applied by the Lambda when not
   * set.
   * @default Duration.seconds(30)
   */
  readonly backoffRate?: Duration;
  /**
   * Upper bound on the delay applied to each replayed message. Applied by the
   * Lambda when not set.
   * @default Duration.minutes(15)
   */
  readonly maximumDelay?: Duration;
  /**
   * Whether to add full jitter to the backoff delay. Applied by the Lambda
   * when not set.
   * @default false
   */
  readonly useJitter?: boolean;
  /**
   * Log retention for the replayer Lambda's log group.
   * @default - keep logs indefinitely
   */
  readonly logRetention?: aws_logs.RetentionDays;
  /**
   * Name of the replayer Lambda function.
   * @default - generated by AWS CloudFormation
   */
  readonly functionName?: string;
  /**
   * Additional environment variables for the replayer Lambda.
   * @default - no additional environment variables
   */
  readonly environment?: { [key: string]: string };
  /**
   * Override the replayer Lambda code. Defaults to the prebuilt Rust binary
   * shipped with this package.
   * @default - prebuilt Rust binary bundled with this package
   */
  readonly code?: aws_lambda.Code;
  /**
   * SSM parameter path under which per-queue replay configs are stored.
   * @default "/sqs-replay/queues/"
   */
  readonly configPath?: string;
}

/**
 * An SQS queue with a replay queue and a DLQ, plus a replayer Lambda that
 * sends redriven messages back to the source queue with exponential backoff.
 */
export class SqsQueueWithReplay extends Construct {
  /**
   * The dead letter queue, the final resting place for messages that exceed
   * their replay attempts.
   */
  public readonly deadLetterQueue: aws_sqs.IQueue;
  /**
   * The replay queue, where redriven messages land before being replayed.
   */
  public readonly replayQueue: aws_sqs.IQueue;
  /**
   * The main queue.
   */
  public readonly queue: aws_sqs.IQueue;
  /**
   * The replayer Lambda function.
   */
  public readonly replayer: aws_lambda.IFunction;

  constructor(scope: Construct, id: string, props: SqsQueueWithReplayProps = {}) {
    super(scope, id);

    const { fifo = false, visibilityTimeout = Duration.seconds(18), maxReceiveCount = 5 } = props;

    this.deadLetterQueue = new aws_sqs.Queue(this, 'DeadLetterQueue', {
      fifo,
    });

    this.replayQueue = new aws_sqs.Queue(this, 'ReplayQueue', {
      fifo,
      visibilityTimeout,
      deadLetterQueue: { queue: this.deadLetterQueue, maxReceiveCount },
    });

    this.queue = new aws_sqs.Queue(this, 'Queue', {
      fifo,
      visibilityTimeout,
      deadLetterQueue: { queue: this.replayQueue, maxReceiveCount },
    });

    const replayer = new SqsReplayer(this, 'Replayer', {
      sourceQueue: this.queue,
      replayQueue: this.replayQueue,
      maxAttempts: props.maxAttempts,
      backoffRate: props.backoffRate,
      maximumDelay: props.maximumDelay,
      useJitter: props.useJitter,
      logRetention: props.logRetention,
      functionName: props.functionName,
      environment: props.environment,
      code: props.code,
      configPath: props.configPath,
    });
    this.replayer = replayer.replayer;
  }
}
