import { aws_ec2, aws_lambda, aws_lambda_event_sources, aws_logs, aws_sqs, aws_ssm, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { SqsReplayerSingleton } from './sqs-replayer-singleton';

export interface SqsReplayerProps {
  /**
   * Queue to send messages back to.
   */
  readonly sourceQueue: aws_sqs.IQueue;
  /**
   * Queue that triggers the replayer, typically the DLQ of `sourceQueue`.
   */
  readonly replayQueue: aws_sqs.IQueue;
  /**
   * Maximum replay attempts before a message is reported as a batch item
   * failure. Applied by the Lambda when not set.
   * @default 5
   */
  readonly maxAttempts?: number;
  /**
   * Multiplier for the backoff calculation. Applied by the Lambda when not
   * set.
   * @default Duration.seconds(30)
   */
  readonly backoffRate?: Duration;
  /**
   * Upper bound on the delay applied to each replayed message. Applied by the
   * Lambda when not set.
   * @default Duration.minutes(15)
   */
  readonly maximumDelay?: Duration;
  /**
   * Whether to add full jitter to the backoff delay. Applied by the Lambda
   * when not set.
   * @default false
   */
  readonly useJitter?: boolean;
  /**
   * Memory allocated to the replayer Lambda. Applies to the shared Lambda the
   * first time it is created.
   * @default 512
   */
  readonly memorySize?: number;
  /**
   * Timeout for the replayer Lambda. Applies to the shared Lambda the first
   * time it is created.
   * @default Duration.seconds(10)
   */
  readonly timeout?: Duration;
  /**
   * Log retention for the replayer Lambda's log group. Applies to the shared
   * Lambda the first time it is created.
   * @default - keep logs indefinitely
   */
  readonly logRetention?: aws_logs.RetentionDays;
  /**
   * Name of the replayer Lambda function. Applies to the shared Lambda the
   * first time it is created.
   * @default - generated by AWS CloudFormation
   */
  readonly functionName?: string;
  /**
   * VPC to place the replayer Lambda in. Applies to the shared Lambda the
   * first time it is created.
   * @default - no VPC
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * Subnets to place the replayer Lambda in. Only used when `vpc` is set.
   * @default - private subnets of `vpc`
   */
  readonly vpcSubnets?: aws_ec2.SubnetSelection;
  /**
   * Additional environment variables for the replayer Lambda. Applies to the
   * shared Lambda the first time it is created.
   * @default - no additional environment variables
   */
  readonly environment?: { [key: string]: string };
  /**
   * Override the Lambda code. Defaults to the prebuilt Rust binary shipped
   * with this package. Applies to the shared Lambda the first time it is
   * created.
   * @default - prebuilt Rust binary bundled with this package
   */
  readonly code?: aws_lambda.Code;
  /**
   * SSM parameter path under which per-queue replay configs are stored.
   * Applies to the shared Lambda the first time it is created.
   * @default "/sqs-replay/queues/"
   */
  readonly configPath?: string;
}

/**
 * Registers a replay queue with the app's shared replayer Lambda. The Lambda
 * resolves the destination queue from SSM Parameter Store using each event's
 * replay queue ARN, and replays messages back to it with exponential backoff.
 */
export class SqsReplayer extends Construct {
  /**
   * The shared replayer Lambda function.
   */
  public readonly replayer: aws_lambda.IFunction;

  constructor(scope: Construct, id: string, props: SqsReplayerProps) {
    super(scope, id);

    const singleton = SqsReplayerSingleton.of(this, {
      memorySize: props.memorySize,
      timeout: props.timeout,
      logRetention: props.logRetention,
      functionName: props.functionName,
      vpc: props.vpc,
      vpcSubnets: props.vpcSubnets,
      environment: props.environment,
      code: props.code,
      configPath: props.configPath,
    });

    const config: { [key: string]: string | number | boolean } = {
      replayQueueArn: props.replayQueue.queueArn,
      destinationQueueUrl: props.sourceQueue.queueUrl,
    };
    if (props.maxAttempts !== undefined) {
      config.maxAttempts = props.maxAttempts;
    }
    if (props.backoffRate !== undefined) {
      config.backoffRate = props.backoffRate.toSeconds();
    }
    if (props.maximumDelay !== undefined) {
      config.maximumDelay = props.maximumDelay.toSeconds();
    }
    if (props.useJitter !== undefined) {
      config.useJitter = props.useJitter;
    }

    const parameterName = `${singleton.configPath}${sanitize(this.node.path)}`;
    new aws_ssm.StringParameter(this, 'Config', {
      parameterName,
      stringValue: JSON.stringify(config),
    });

    singleton.replayer.addEventSource(
      new aws_lambda_event_sources.SqsEventSource(props.replayQueue, {
        batchSize: 1,
        reportBatchItemFailures: true,
      }),
    );

    props.sourceQueue.grantSendMessages(singleton.replayer);

    this.replayer = singleton.replayer;
  }
}

/** Keeps construct paths valid as SSM parameter names. */
const sanitize = (value: string) => value.replace(/[^a-zA-Z0-9_./-]/g, '-');
